language: node_js
node_js:
  - 12
before_deploy: 
- sudo touch .npmignore
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_KEY"
  on:
    tags: true
    branch: main